# Generated by Django 4.1.7 on 2023-03-31 18:08

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=255)),
                ('description', models.CharField(default='none', max_length=255)),
                ('requirements', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=20)),
                ('npc_id', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('drone_team_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('battery_capacity', models.IntegerField()),
                ('battery_remaining', models.IntegerField()),
                ('capabilities', models.JSONField(blank=True, default=dict, null=True)),
                ('upgrade_slots', models.IntegerField()),
                ('team_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DroneTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('drones', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('player_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('credits', models.IntegerField()),
                ('reputation', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TulipField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField()),
                ('soil_type', models.CharField(max_length=50)),
                ('contract_id', models.IntegerField()),
                ('drone_team_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TulipPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tulip_type', models.CharField(max_length=50)),
                ('growth_stage', models.IntegerField()),
                ('health', models.FloatField()),
                ('field_id', models.IntegerField()),
            ],
        ),
    ]
